language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update
  - composer install --no-interaction

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - vendor/bin/phpunit --verbose